### ISSUE TITLE
Link to Asana API keys docs refers to nonexistent anchor

### ISSUE THREAD

**Issue by trejkaz** [goncaloborrega/TrelloToAsana#2]
In the example config file, there is this:

      # your Asana API Key - http://developer.asana.com/documentation/#api_keys

But if you go to that page, there is no anchor with that name.

**Comment by trejkaz** [comment]
The correct link appears to be https://asana.com/developers/documentation/getting-started/auth#api-key

**Comment by goncaloborrega** [comment]
Thank you. Updated.
